# Production values
namespace: interview-example-project

postgresDatabase:
  componentName: postgres
  persistentVolumePath: /var/lib/postgresql/data/pg_data
  persistentVolumeClaim: postgres-pvc

backend:
  componentName: backend-api
  currentVersion: 1.3.5

frontend:
  componentName: frontend-react
  currentVersion: 1.3.5

ingress:
  url: gke-test.ruecker.dev

certificate:
  issuer: letsencrypt-prod
  url: https://acme-v02.api.letsencrypt.org/directory



