apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: interview-example-project
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:15.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pg_data
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pg_data
              name: postgres-pvc
              subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 120M
