apiVersion: v1
kind: Service
metadata:
  name: frontend-ip-service
spec:
  type: ClusterIP
  selector:
    component: frontend-react
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
