apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-database
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.postgresDatabase.componentName }}
  serviceName: {{ .Values.postgresDatabase.componentName }}
  template:
    metadata:
      labels:
        component: {{ .Values.postgresDatabase.componentName }}
    spec:
      containers:
        - name: {{ .Values.postgresDatabase.componentName }}
          image: docker.io/postgres:15.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: PGDATA
              value: {{ .Values.postgresDatabase.persistentVolumePath }}
          volumeMounts:
            - mountPath: {{ .Values.postgresDatabase.persistentVolumePath }}
              name: {{ .Values.postgresDatabase.persistentVolumeClaim }}
              subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.postgresDatabase.persistentVolumeClaim }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 120M
