apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.postgresDatabase.componentName }}
  ports:
    - port: 5433
      targetPort: 5432
