apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.backend.componentName }}
  template:
    metadata:
      labels:
        component: {{ .Values.backend.componentName }}
    spec:
      containers:
        - name: {{ .Values.backend.componentName }}
          image: docker.io/21321321421441/interview-example-project-backend:{{ .Values.backend.currentVersion }}
          ports:
            - containerPort: 4667
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
