apiVersion: v1
kind: Service
metadata:
  name: frontend-ip-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.frontend.componentName }}
  ports:
    - name: http
      port: 80
      targetPort: 80
