apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interview-example-ingress-service
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/issuer: {{ .Values.certificate.issuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.url }}
      secretName: interview-example-tls
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-ip-service
                port:
                  number: 4667
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-ip-service
                port:
                  number: 80
