name: Test interview-example-project

on:
  push:
    branches:
      - master

jobs:
  setup-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          architecture: x64
          cache: 'maven'

      - name: Package the application
        working-directory: backend
        run: |
          echo "-----------------------------------"
          echo "Using maven version:"
          sh -c "mvn -v | grep 'Apache Maven'"
          echo "-----------------------------------"
          mvn package -DskipIntegrationTests=true
  run-backend-tests:
    runs-on: ubuntu-latest
    needs: [ setup-backend ]
    steps:
      - name: Run maven tests
        working-directory: backend
        run: mvn test -DskipIntegrationTests=true
